name: Evolu Design Document (EDD)
description: A formal design for a proposed Evolu feature or change.
title: "EDD-XXX: <Concise title>"

labels: [edd, status: draft]

body:
  - type: textarea
    id: what
    attributes:
      label: What
      description: What is this EDD about?
      placeholder: Describe the feature or change this design proposes.
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why
      description: Why is this needed?
      placeholder: Explain the problem this solves or the opportunity it enables.
    validations:
      required: true

  - type: textarea
    id: how
    attributes:
      label: How
      description: How will this be implemented?
      placeholder: Outline the approach, technical steps, or affected parts of the system.
    validations:
      required: true

  - type: textarea
    id: related
    attributes:
      label: Related
      description: Link to any related EDDs, issues, discussions, or resources.
      placeholder: List any relevant context or prior work.
    validations:
      required: false
