name: Evolu Design Document (EDD)
description: Propose a change or addition to Evolu
title: "EDD-XXX: <short title>"
labels: [edd, status: draft]
body:
  - type: input
    id: title
    attributes:
      label: Short Title
      placeholder: Expiring CRDT Messages
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      placeholder: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      placeholder: Describe the design or behavior in detail
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale & Tradeoffs
      placeholder: Why this design? What were the alternatives?
    validations:
      required: false

  - type: textarea
    id: compatibility
    attributes:
      label: Compatibility / Migration
      placeholder: Will this break existing apps? How to migrate?
    validations:
      required: false
