name: Evolu Evolution Proposal (EEP)
description: A formal design for a proposed Evolu feature or change.
title: "EEP-XXX: <Descriptive title>"

labels: [eep]

body:
  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      placeholder: Brief summary of the feature or change and its purpose.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      placeholder: Why is this needed? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      placeholder: How will this be implemented? Technical sketch, affected parts, or steps.
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links
      placeholder: Related EEPs, issues, discussions, or external resources.
    validations:
      required: false
